name: Build and deploy sqlproj to an DW

on:
  workflow_dispatch:

env:
  DIST_PATH: .\dist

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v2
      
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
        
      - name: build sqlproj
        working-directory: Magellan.DataWarehouse.YMDB
        run: msbuild Magellan.DataWarehouse.YMDB.sln /t:rebuild /p:Configuration="Release"
        
      - name: create dist
        run: |
          $EXIST=(Test-Path '${{env.DIST_PATH}'})
          if($EXIST){ remove-Item -Recurse -Force '${{env.DIST_PATH}' }
          New-Item '${{env.DIST_PATH}' -Type directory -Force
          
      - name: Collect Dacpac files
        run: |
          $files=@(Get-ChildItem -Path 'Magellan.DataWarehouse.YMDB' -Filter "*.dacpac" -recurse)
          foreach($f in $files){ xcopy $f.FullName '${{env.DIST_PATH}' /y }
      
      - name: Generate SQLScript
        run: |
          import-module FindSqlPackagePath.ps1 -Force
          $sqlpackage = Get-SqlPackageOnTargetMachine
          &$sqlpackage /Action:Script /OutputPath:'${{env.DIST_PATH}\YMDB_${{github.job}}.sql' /DeployReportPath:'${{env.DIST_PATH}\${{github.job}}.xml' /SourceFile:'${{env.DIST_PATH}\YMDB_Magellan.DataWarehouse.YMDB.dacpac' /TargetConnectionString:${{ secrets.DW_CONN_STRING }}
          
      

        
      
      
